---
- name: Install EPEL repo.
  yum:
    name: epel-release
    state: present

- name: Import Remi GPG key.
  rpm_key:
    key: "https://rpms.remirepo.net/RPM-GPG-KEY-remi"
    state: present

- name: Install Remi repo.
  yum:
    name: "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
    state: present

- name: Ensure firewalld is stopped (since this is a test server).
  service:
    name: firewalld
    state: stopped

- name: Install Node.js and npm.
  package:
    name: npm
    state: present
    enablerepo: epel

- name: Install Forever (to run our Node.js app).
  npm:
    name: forever
    global: yes
    state: present
