---
- name: Install Apache
  package:
    name: "{{ apache_package }}"
    state: present

- name: Copy test config file
  copy:
    src: files/test.conf
    dest: "{{ apache_config_dir }}/test.conf"
  notify: restart apache

- name: Ensure Apache is started now and at boot
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: true
