---
- name: Install Apache
  hosts: ubuntu
  become: true

  # vars:
  #   apache_package: httpd
  #   apache_service: httpd
  #   apache_config_dir: /etc/httpd/conf.d

  pre_tasks:
    - name: Load variable files
      include_vars: "{{ item }}"
      with_first_found:
        - "vars/apache_{{ ansible_os_family }}.yml"
        - vars/apache_default.yml

  handlers:
    - name: restart apache
      service:
        name: "{{ apache_service }}"
        state: restarted

  tasks:
    - name: Install Apache
      package:
        name: "{{ apache_package }}"
        state: present

    - name: Copy test config file
      copy:
        src: files/test.conf
        dest: "{{ apache_config_dir }}/test.conf"
      notify: restart apache

    - name: Ensure Apache is started now and at boot
      service:
        name: "{{ apache_service }}"
        state: started
        enabled: true
