# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/ubuntu1604"

  config.ssh.insert_key = false

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |v|
    v.memory = 256
    v.linked_clone=true
  end

  config.vm.define "solr_app" do |solr_app|
    solr_app.vm.hostname = "solr-app.test"
    solr_app.vm.network :private_network, ip: "192.168.60.4"
  end

end
